### PR TITLE
Downgrade the minimum deployment target to iOS 7.0

### PR DESCRIPTION
**Pull request by yeahdongcn**

### CODE REVIEW

**Comment by yeahdongcn** [comment]
Thank you!

**Comment by yeahdongcn** [comment]
Could you push the new spec to cocoapods?

**Comment by dymx101** [comment]
Thanks for the contribution, I'll push it in 2 days.

**Comment by dymx101** [comment]
Hey yeahdongcn, The new spec has been pushed, thanks!

**Pull request merged**
